### ISSUE TITLE
Docker network driver issue

### ISSUE THREAD

**Issue by Gaz492** [Steccas/stecCA#2]
Not sure if this is something im doing wrong/missing but when I try and set this up I get the following message 
Creating network "stecca_canet" with the default driver
ERROR: plugin "bridge" not found

EDIT:
Forgot to add that this is on Ubuntu server 20.04

**Comment by Steccas** [comment]
I think it is a problem with your docker, bridge is one of the default docker networks.

Are you on Windows?

**Comment by Gaz492** [comment]
I'm on Linux (ubuntu 20.04), google is not being much help as most of the issues are windows based.
Listing the Docker networks does show that bridge is there so I'm not entirely sure what the issue is as I have tried 2 different servers now as well.
```
/stecCA# docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
2014e914fb7a   bridge    bridge    local
6ac52cb35f23   host      host      local
b3978049d828   none      null      local
```

**Comment by Steccas** [comment]
Mmmh you find Windows stuff because it is a common Windows problem.
Have you enabled forwarding in systemctl and firewall?
Do you manage to create a bridge network via Docker CLI?

Wich Docker and Docker-Compose version are you in?

I'm gonna rerun in a Ubuntu VM tomorrow anyways

**Comment by gianpiero** [comment]
Just adding to this thread. I have the same issue.  I am on Linux mint 20. 

```
 docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
b588ffab2352   bridge    bridge    local
1ec562f677b5   host      host      local
e3d3e307712a   none      null      local
```

```
$ docker -v
Docker version 20.10.6, build 370c289
```

```
$ docker-compose -v
docker-compose version 1.25.0, build unknown
```

**Comment by Steccas** [comment]
Please try to update your docker-compose, it is several versions old.

Just in case, is any of you using WSL?

**Comment by Gaz492** [comment]
Not using WSL, tried on a raspberry pi and on a hetzner cloud server running ubuntu server 20.04
Was able to create a bridge using docker cli with no issues.

Docker versions:
```
Docker version 20.10.6, build 370c289
docker-compose version 1.29.1, build c34c88b2
```

**Comment by gianpiero** [comment]
I updated docker-compose:

```
$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

same error. 

I am not using WSL. Mint Linux 20

**Comment by Steccas** [comment]
In some cases this error can occur, I did modify the compose slightly. It should be solved now, please confirm so we can close the issue.

**Comment by Gaz492** [comment]
That change seems to have fixed the issue :D

**Comment by Steccas** [comment]
Great, I'm closing!
