### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by fbulatovsky** [Steccas/stecCA#7]
The command '/bin/sh -c apt-get update &&     apt-get -y --no-install-recommends upgrade &&     apt-get install -y --no-install-recommends libpq-dev curl build-essential locales libffi-dev libsasl2-dev libldap2-dev         dh-autoreconf git python3-dev python3-pip python3-venv python3-wheel nodejs npm &&     locale-gen en_US.UTF-8 && export LC_ALL=en_US.UTF-8 &&     npm config set registry http://registry.npmjs.org/ &&     npm install npm -g &&     echo "Running with nodejs:" && node -v &&     python3 -m venv /opt/venv &&     echo "Running with python:" && /opt/venv/bin/python3 -c 'import platform; print(platform.python_version())' &&     /opt/venv/bin/python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel &&     /opt/venv/bin/python3 -m pip install --no-cache-dir -e . &&     npm install --unsafe-perm &&     node_modules/.bin/gulp --cwd /opt/lemur build &&     node_modules/.bin/gulp --cwd /opt/lemur package &&     npm cache clean --force &&     rm -rf node_modules &&     python3 -c 'print(" \033[32m BUILDER DONE \033[0m ")'' returned a non-zero code: 1
ERROR: Service 'lemur' failed to build : Build failed

**Comment by Steccas** [comment]
What is this, place format the issue and describe it in an understandable way.

Otherwise it will be deleted.
